### ISSUE TITLE
Preview does not match question formatting

### ISSUE THREAD

**Issue by Joeyn1993** [hkhosrav/RiPPLE-Core#321]
Due to tag bleaching. 

Preview should show exactly what the user will see.

**Comment by Joeyn1993** [comment]
Will be closely related to #314

**Comment by zicozico77** [comment]
Current fix by adding more elements to the current white-list for the bleacher. Only a partial solution as copying or trying to use other non considered html tags will just result in the same bug and having to add them manually as well.

Reason for not doing a black-list is that in the case of a white-list worst case scenario, a student will end up with html tags in their code. In the case of a black list worst case scenario, some type of html statement is not considered and creates a vulnerability in the whole application. 

Currently, we do not store the preview data on the database since its not supposed to be saved yet, so the bleacher never touches it, hence why formatting does not match. The bleacher is also a python package so it cannot be used in the client side. Using a client side bleacher would also create the inconsistency of using two different programs and expect the same result, as well as having to keep both of them updated.

**Comment by zicozico77** [comment]
also took the fullscreen and the preview plugins:
fullscreen => was messing up the file format
preview=> Preview feature already in ripple question creation
